{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "conductor-oss-conductor.serviceAccountName" . }}
  labels:
    {{- include "conductor-oss-conductor.labels" . | nindent 4 }}
  {{- with (include "conductor-oss-conductor.serviceAccountAnnotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
