apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ignite.fullname" . }}
  labels:
    {{- include "ignite.labels" . | nindent 4 }}
  {{- with (include "ignite.annotations" .) }}
  annotations:
      {{- . | nindent 4 }}
  {{- end }}
data:
  ignite-config.xml: |
    <?xml version="1.0" encoding="UTF-8"?>

    <!--
      Licensed to the Apache Software Foundation (ASF) under one or more
      contributor license agreements.  See the NOTICE file distributed with
      this work for additional information regarding copyright ownership.
      The ASF licenses this file to You under the Apache License, Version 2.0
      (the "License"); you may not use this file except in compliance with
      the License.  You may obtain a copy of the License at

           http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.
    -->

    <beans xmlns="http://www.springframework.org/schema/beans"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns:util="http://www.springframework.org/schema/util"
           xsi:schemaLocation="
            http://www.springframework.org/schema/beans
            http://www.springframework.org/schema/beans/spring-beans.xsd
            http://www.springframework.org/schema/util
            http://www.springframework.org/schema/util/spring-util.xsd">

        {{- if .Values.extraBeans }}
        {{ .Values.extraBeans | nindent 8 }}
        {{- end }}

        <bean class="org.apache.ignite.configuration.IgniteConfiguration" id="ignite.cfg">
            <property name="authenticationEnabled" value="{{ .Values.authentication.enabled }}"/>
            <property name="peerClassLoadingEnabled" value="{{ .Values.peerClassLoadingEnabled }}"/>
            <property name="failureDetectionTimeout" value="{{ .Values.timeouts.failureDetectionTimeout }}"/>
            <property name="clientFailureDetectionTimeout" value="{{ .Values.timeouts.clientFailureDetectionTimeout }}"/>
            <property name="networkTimeout" value="{{ .Values.timeouts.networkTimeout }}"/>
            {{- if .Values.threadPools.publicThreadPoolSize }}
            <property name="publicThreadPoolSize" value="{{ .Values.threadPools.publicThreadPoolSize }}"/>
            {{- end }}
            {{- if .Values.threadPools.systemThreadPoolSize }}
            <property name="systemThreadPoolSize" value="{{ .Values.threadPools.systemThreadPoolSize }}"/>
            {{- end }}
            {{- if .Values.threadPools.queryThreadPoolSize }}
            <property name="queryThreadPoolSize" value="{{ .Values.threadPools.queryThreadPoolSize }}"/>
            {{- end }}
            {{- if .Values.threadPools.serviceThreadPoolSize }}
            <property name="serviceThreadPoolSize" value="{{ .Values.threadPools.serviceThreadPoolSize }}"/>
            {{- end }}
            {{- if .Values.threadPools.stripedPoolSize }}
            <property name="stripedPoolSize" value="{{ .Values.threadPools.stripedPoolSize }}"/>
            {{- end }}
            {{- if .Values.threadPools.dataStreamerThreadPoolSize }}
            <property name="dataStreamerThreadPoolSize" value="{{ .Values.threadPools.dataStreamerThreadPoolSize }}"/>
            {{- end }}
            <property name="segmentationPolicy" value="RESTART_JVM" />
            <property name="segmentationResolveAttempts" value="5" />
            <property name="shutdownPolicy" value="GRACEFUL"/>

            <property name="gridLogger">
                <bean class="org.apache.ignite.logger.log4j2.Log4J2Logger">
                    <constructor-arg type="java.lang.String" value="/opt/ignite/apache-ignite/config/log4j2-config.xml"/>
                </bean>
            </property>

            <property name="includeEventTypes">
                <list>
                    <util:constant static-field="org.apache.ignite.events.EventType.EVT_CLUSTER_STATE_CHANGED"/>
                    <util:constant static-field="org.apache.ignite.events.EventType.EVT_NODE_JOINED"/>
                    <util:constant static-field="org.apache.ignite.events.EventType.EVT_NODE_LEFT"/>
                    <util:constant static-field="org.apache.ignite.events.EventType.EVT_NODE_FAILED"/>
                    <util:constant static-field="org.apache.ignite.events.EventType.EVT_NODE_SEGMENTED"/>
                    <util:constant static-field="org.apache.ignite.events.EventType.EVT_CLIENT_NODE_DISCONNECTED"/>
                    <util:constant static-field="org.apache.ignite.events.EventType.EVT_CLIENT_NODE_RECONNECTED"/>
                    <util:constant static-field="org.apache.ignite.events.EventType.EVT_CACHE_REBALANCE_PART_DATA_LOST"/>
                </list>
            </property>

            {{- if .Values.userAttributes }}
            <property name="userAttributes">
                {{- .Values.userAttributes | nindent 16 }}
            </property>
            {{- end }}

            {{- if .Values.binaryConfiguration }}
            <property name="binaryConfiguration">
                {{- .Values.binaryConfiguration | nindent 16 }}
            </property>
            {{- end }}

            {{- if .Values.cacheConfiguration }}
            <property name="cacheConfiguration">
                {{- .Values.cacheConfiguration | nindent 16 }}
            </property>
            {{- end }}

            {{- if .Values.cacheKeyConfiguration }}
            <property name="cacheKeyConfiguration">
                {{- .Values.cacheKeyConfiguration | nindent 16 }}
            </property>
            {{- end }}

            <property name="clientConnectorConfiguration">
                <bean class="org.apache.ignite.configuration.ClientConnectorConfiguration">
                    {{- if .Values.ssl.enabled }}
                    <!--
                        SSL/TLS for Thin Clients and JDBC/ODBC.
                        Re-use the SSLContextFactory configured for nodes.
                    -->
                    <property name="sslEnabled" value="{{ .Values.ssl.clientConnector.enabled }}"/>
                    <property name="sslClientAuth" value="{{ .Values.ssl.clientConnector.clientAuth }}"/>
                    {{- end }}

                    {{- .Values.clientConnector.extraConfiguration | nindent 20 }}
                </bean>
            </property>

            <!-- Ignite Data Storage Configuration -->
            <property name="dataStorageConfiguration">
                <bean class="org.apache.ignite.configuration.DataStorageConfiguration">
                    <property name="metricsEnabled" value="{{ .Values.metrics.enabled }}"/>

                    <!-- Ignite Default Data Region Configuration -->
                    <property name="defaultDataRegionConfiguration">
                        <bean class="org.apache.ignite.configuration.DataRegionConfiguration">
                            <property name="persistenceEnabled" value="{{ .Values.persistence.enabled }}"/>
                            <property name="metricsEnabled" value="{{ .Values.metrics.enabled }}"/>
                            <property name="maxSize" value="{{ mul (required "A valid memory.offHeapMb is required!" .Values.memory.offHeapMb) 1024 1024 }}"/>
                            {{- if and (not .Values.persistence.enabled) .Values.dataStorage.pageEvictionMode }}
                            <property name="pageEvictionMode" value="{{ .Values.dataStorage.pageEvictionMode }}"/>
                            {{- end }}
                        </bean>
                    </property>

                    {{- if .Values.persistence.enabled }}
                    <!--
                       Sets a path to the root directory where data and indexes are
                       to be persisted. It's assumed the directory is on a dedicated disk.
                    -->
                    <property name="storagePath" value="/storage"/>

                    <!--
                        Sets a path to the directory where WAL is persisted.
                        It's assumed the directory is on a dedicated disk.
                    -->
                    <property name="walPath" value="/wal"/>

                    <!--
                        Sets a path to the directory where WAL archive is persisted.
                        It's assumed the directory is on the same drive with the WAL files.
                    -->
                    <property name="walArchivePath" value="/wal/archive"/>

                    <property name="walCompactionEnabled" value="true"/>
                    <property name="walSegmentSize" value="{{ mul 256 1024 1024 }}"/>
                    <property name="walMode" value="LOG_ONLY"/>
                    {{- end }}

                    {{- .Values.dataStorage.extraConfiguration | nindent 20 }}
                </bean>
            </property>

            {{- if .Values.executorConfiguration }}
            <property name="executorConfiguration">
                {{- .Values.executorConfiguration | nindent 16 }}
            </property>
            {{- end }}

            {{- if .Values.memoryConfiguration }}
            <property name="memoryConfiguration">
                {{- .Values.memoryConfiguration | nindent 16 }}
            </property>
            {{- end }}

            {{- if .Values.serviceConfiguration }}
            <property name="serviceConfiguration">
                {{- .Values.serviceConfiguration | nindent 16 }}
            </property>
            {{- end }}

            {{- if .Values.sqlConfiguration }}
            <property name="sqlConfiguration">
                {{- .Values.sqlConfiguration | nindent 16 }}
            </property>
            {{- end }}

            {{- if .Values.transactionConfiguration }}
            <property name="transactionConfiguration">
                {{- .Values.transactionConfiguration | nindent 16 }}
            </property>
            {{- end }}

            {{- if .Values.ssl.enabled }}
            <!-- SSL/TLS for Nodes -->
            <property name="sslContextFactory">
                <bean class="org.apache.ignite.ssl.SslContextFactory">
                    <property name="keyAlgorithm" value="{{ .Values.ssl.keyAlgorithm }}"/>
                    <property name="keyStoreFilePath" value="{{ .Values.ssl.keyStoreFilePath }}"/>
                    <property name="keyStorePassword" value="${IGNITE_SSL_KS_PASS}"/>
                    <property name="keyStoreType" value="{{ .Values.ssl.keyStoreType }}"/>
                    <property name="trustStoreFilePath" value="{{ .Values.ssl.trustStoreFilePath }}"/>
                    <property name="trustStorePassword" value="${IGNITE_SSL_TS_PASS}"/>
                    <property name="trustStoreType" value="{{ .Values.ssl.trustStoreType }}"/>
                    <property name="protocol" value="{{ .Values.ssl.protocol }}"/>
                </bean>
            </property>
            {{- end }}

            {{- if .Values.collisionSpi }}
            <property name="collisionSpi">
                {{- .Values.collisionSpi | nindent 16 }}
            </property>
            {{- end }}

            {{- if .Values.communicationSpi }}
            <property name="communicationSpi">
                {{ .Values.communicationSpi | nindent 16 }}
            </property>
            {{- end }}

            {{- if .Values.deploymentSpi }}
            <property name="deploymentSpi">
                {{- .Values.deploymentSpi | nindent 16 }}
            </property>
            {{- end }}

            <!-- Explicitly configure TCP discovery SPI to provide list of initial nodes. -->
            <property name="discoverySpi">
                <bean class="org.apache.ignite.spi.discovery.tcp.TcpDiscoverySpi">
                    <property name="ipFinder">
                        <!--
                            Enables Kubernetes IP finder and setting custom namespace and service names.
                        -->
                        <bean class="org.apache.ignite.spi.discovery.tcp.ipfinder.kubernetes.TcpDiscoveryKubernetesIpFinder">
                            <property name="namespace" value="{{ .Release.Namespace }}"/>
                            <property name="serviceName" value="{{ include "ignite.fullname" . }}-svc-headless"/>
                        </bean>
                    </property>
                </bean>
            </property>

            {{- if .Values.encryptionSpi }}
            <property name="encryptionSpi">
                {{- .Values.encryptionSpi | nindent 16 }}
            </property>
            {{- end }}

            {{- if .Values.failoverSpi }}
            <property name="failoverSpi">
                {{- .Values.failoverSpi | nindent 16 }}
            </property>
            {{- end }}

            {{- if .Values.loadBalancingSpi }}
            <property name="loadBalancingSpi">
                {{- .Values.loadBalancingSpi | nindent 16 }}
            </property>
            {{- end }}

            {{- if .Values.metrics.enabled }}
            <property name="metricsUpdateFrequency" value="5000"/>

            <property name="metricExporterSpi">
                <list>
                    <bean class="org.apache.ignite.spi.metric.opencensus.OpenCensusMetricExporterSpi">
                        <property name="period" value="10000" />
                    </bean>
                </list>
            </property>
            {{- end }}

            {{- if .Values.tracing.enabled }}
            <property name="tracingSpi">
                <bean class="org.apache.ignite.spi.tracing.opencensus.OpenCensusTracingSpi"/>
            </property>
            {{- end }}
        </bean>
    </beans>
  log4j2-config.xml: |
    <?xml version="1.0" encoding="UTF-8"?>

    <!--
      Licensed to the Apache Software Foundation (ASF) under one or more
      contributor license agreements.  See the NOTICE file distributed with
      this work for additional information regarding copyright ownership.
      The ASF licenses this file to You under the Apache License, Version 2.0
      (the "License"); you may not use this file except in compliance with
      the License.  You may obtain a copy of the License at

           http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.
    -->

    <Configuration monitorInterval="60">
        <Appenders>
            <Console name="CONSOLE" target="SYSTEM_OUT">
                <!-- Add the `disableAnsi="true"` property to the pattern layout if you want to disable colors in the console output. -->
                <PatternLayout
                    pattern="[%d{ISO8601}]%highlight{[%-5p]}{INFO=green, DEBUG=green bold, TRACE=blue}%style{[%t]}{magenta}%style{[%c{1}]}{cyan}%notEmpty{[%markerSimpleName]} %m%n"/>
                <ThresholdFilter level="WARN" onMatch="DENY" onMismatch="ACCEPT"/>
            </Console>

            <Console name="CONSOLE_WARN" target="SYSTEM_OUT">
                <!-- Add the `disableAnsi="true"` property to the pattern layout if you want to disable colors in the console output. -->
                <PatternLayout pattern="%highlight{[%d{ISO8601}][%-5p][%t][%c{1}] %m%n}{WARN=yellow bold}"/>
                <ThresholdFilter level="WARN" onMatch="ACCEPT" onMismatch="DENY"/>
            </Console>

            <Console name="CONSOLE_ERR" target="SYSTEM_ERR">
                <!-- Add the `disableAnsi="true"` property to the pattern layout if you want to disable colors in the console output. -->
                <PatternLayout pattern="%highlight{[%d{ISO8601}][%-5p][%t][%c{1}] %m%n}{ERROR=bright red}"/>
            </Console>

            <File name="CONSISTENCY" fileName="${sys:IGNITE_HOME}/work/log/consistency.log">
                <PatternLayout>
                    <Pattern>"[%d{ISO8601}][%-5p][%t][%c{1}] %m%n"</Pattern>
                </PatternLayout>
            </File>

            <Routing name="FILE">
                <Routes pattern="$${sys:appId}$${sys:nodeId}">
                    <Route>
                        <RollingFile name="Rolling-${sys:appId}${sys:nodeId}" fileName="${sys:IGNITE_HOME}/work/log/${sys:appId}${sys:nodeId}.log"
                                     filePattern="${sys:IGNITE_HOME}/work/log/${sys:appId}${sys:nodeId}-%i-%d{yyyy-MM-dd}.log.gz">
                            <PatternLayout pattern="[%d{ISO8601}][%-5p][%t][%c{1}]%notEmpty{[%markerSimpleName]} %m%n"/>
                            <Policies>
                                <TimeBasedTriggeringPolicy interval="6" modulate="true" />
                                <SizeBasedTriggeringPolicy size="10 MB" />
                            </Policies>
                        </RollingFile>
                    </Route>
                </Routes>
            </Routing>
        </Appenders>

        <Loggers>
            <!--
            <Logger name="org.apache.ignite" level=DEBUG/>
            -->

            <!--
                Uncomment to disable courtesy notices, such as SPI configuration
                consistency warnings.
            -->
            <!--
            <Logger name="org.apache.ignite.CourtesyConfigNotice" level=OFF/>
            -->

            <Logger name="org.springframework" level="WARN"/>
            <Logger name="org.eclipse.jetty" level="WARN"/>

            <Logger name="org.apache.ignite.internal.management.consistency" additivity="false" level="INFO">
                <AppenderRef ref="CONSISTENCY"/>
            </Logger>

            <!--
            Avoid warnings about failed bind attempt when multiple nodes running on the same host.
            -->
            <Logger name="org.eclipse.jetty.util.log" level="ERROR"/>
            <Logger name="org.eclipse.jetty.util.component" level="ERROR"/>

            <Logger name="com.amazonaws" level="WARN"/>

            <Root level="INFO">
                <!-- Uncomment to enable logging to console. -->
                <!--
                <AppenderRef ref="CONSOLE" level="DEBUG"/>
                <AppenderRef ref="CONSOLE_WARN" level="WARN"/>
                -->

                <AppenderRef ref="CONSOLE_ERR" level="ERROR"/>
                <AppenderRef ref="FILE" level="DEBUG"/>
            </Root>
        </Loggers>
    </Configuration>
