{{- if .Values.networkPolicy.create }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.networkPolicy.name | default (include "ignite.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "ignite.labels" . | nindent 4 }}
  {{- with (include "ignite.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  egress: {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  ingress: {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  podSelector:
    matchLabels: {{- include "ignite.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
{{- end }}
