{{- if .Values.ssl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ignite.fullname" . }}-ssl
  labels:
    {{- include "ignite.labels" . | nindent 4 }}
  {{- with (include "ignite.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  client-connector-ks-pass: {{ .Values.ssl.clientConnector.keyStorePassword | b64enc | quote }}
  client-connector-ts-pass: {{ .Values.ssl.clientConnector.trustStorePassword | b64enc | quote }}
  network-ks-pass: {{ .Values.ssl.network.keyStorePassword | b64enc | quote }}
  network-ts-pass: {{ .Values.ssl.network.trustStorePassword | b64enc | quote }}
  rest-ks-pass: {{ .Values.ssl.rest.keyStorePassword | b64enc | quote }}
  rest-ts-pass: {{ .Values.ssl.rest.trustStorePassword | b64enc | quote }}
{{- end }}
