{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ignite.serviceAccountName" . }}
  labels:
    {{- include "ignite.labels" . | nindent 4 }}
  {{- with (include "ignite.serviceAccountAnnotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
