{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clamav-openshift.serviceAccountName" . }}
  labels:
    {{- include "clamav-openshift.labels" . | nindent 4 }}
  {{- with (include "clamav-openshift.serviceAccountAnnotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
