{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "aspnetcore-ignite-server.fullname" . }}
  labels:
    {{- include "aspnetcore-ignite-server.labels" . | nindent 4 }}
  {{- with (include "aspnetcore-ignite-server.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "aspnetcore-ignite-server.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aspnetcore-ignite-server.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
