apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aspnetcore-ignite-server.fullname" . }}
  labels:
    {{- include "aspnetcore-ignite-server.labels" . | nindent 4 }}
  {{- with (include "aspnetcore-ignite-server.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  ignite-user-password: {{ .Values.secrets.igniteUserPassword | b64enc | quote }}
  ssl-key-store-password: {{ .Values.secrets.sslKeyStorePassword | b64enc | quote }}
  ssl-trust-store-password: {{ .Values.secrets.sslTrustStorePassword | b64enc | quote }}
  ssl-client-certificate-password: {{ .Values.secrets.sslClientCertificatePassword | b64enc | quote }}
