{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aspnetcore-ignite-server.serviceAccountName" . }}
  labels:
    {{- include "aspnetcore-ignite-server.labels" . | nindent 4 }}
  {{- with (include "aspnetcore-ignite-server.serviceAccountAnnotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
