apiVersion: v2
appVersion: "3.1.0"
description: Apache Ignite is a distributed database for high-performance computing with in-memory speed.
name: ignite-3
type: application
version: 3.1.0
keywords:
  - java
  - datagrid
  - caching
  - jvm
  - sql
  - key-value
  - nosql
  - distributed
home: https://ignite.apache.org/docs/ignite3/latest/
icon: https://ignite.apache.org/img/logo.svg
sources:
  - https://github.com/apache/ignite-3
maintainers:
  - name: dradoaica
    email: dradoaica@gmail.com
    url: https://dradoaica.blogspot.com/
kubeVersion: ">= 1.26.0"
